window.esdocSearchIndex = [
  [
    "@cedx/ngx-cookies/src/cookie_options.js~cookie_options",
    "variable/index.html#static-variable-COOKIE_OPTIONS",
    "<span>COOKIE_OPTIONS</span> <span class=\"search-result-import-path\">@cedx/ngx-cookies/src/cookie_options.js</span>",
    "variable"
  ],
  [
    "@cedx/ngx-cookies/src/cookie_module.js~cookiemodule",
    "class/src/cookie_module.js~CookieModule.html",
    "<span>CookieModule</span> <span class=\"search-result-import-path\">@cedx/ngx-cookies/src/cookie_module.js</span>",
    "class"
  ],
  [
    "@cedx/ngx-cookies/src/cookie_options.js~cookieoptions",
    "class/src/cookie_options.js~CookieOptions.html",
    "<span>CookieOptions</span> <span class=\"search-result-import-path\">@cedx/ngx-cookies/src/cookie_options.js</span>",
    "class"
  ],
  [
    "@cedx/ngx-cookies/src/cookies.js~cookies",
    "class/src/cookies.js~Cookies.html",
    "<span>Cookies</span> <span class=\"search-result-import-path\">@cedx/ngx-cookies/src/cookies.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "cookieoptions src/cookie_options.js~cookieoptions,cookieoptions",
    "test-file/test/cookie_options_test.js.html#lineNumber10",
    "CookieOptions",
    "test"
  ],
  [
    "cookieoptions#tojson src/cookie_options.js~cookieoptions#tojson,cookieoptions#tojson",
    "test-file/test/cookie_options_test.js.html#lineNumber15",
    "CookieOptions #toJSON()",
    "test"
  ],
  [
    "",
    "test-file/test/cookie_options_test.js.html#lineNumber16",
    "CookieOptions #toJSON() should return a map with default values for a newly created instance",
    "test"
  ],
  [
    "",
    "test-file/test/cookie_options_test.js.html#lineNumber25",
    "CookieOptions #toJSON() should return a non-empty map for an initialized instance",
    "test"
  ],
  [
    "cookieoptions#tostring src/cookie_options.js~cookieoptions#tostring,cookieoptions#tostring",
    "test-file/test/cookie_options_test.js.html#lineNumber38",
    "CookieOptions #toString()",
    "test"
  ],
  [
    "",
    "test-file/test/cookie_options_test.js.html#lineNumber43",
    "CookieOptions #toString() should return a format like \"expires=<expires>; domain=<domain>; path=<path>; secure\" for an initialized instance",
    "test"
  ],
  [
    "",
    "test-file/test/cookie_options_test.js.html#lineNumber39",
    "CookieOptions #toString() should return an empty string for a newly created instance",
    "test"
  ],
  [
    "cookies src/cookies.js~cookies,cookies",
    "test-file/test/cookies_test.js.html#lineNumber11",
    "Cookies",
    "test"
  ],
  [
    "cookies#symbol.iterator cookies#symbol.iterator,cookies#symbol.iterator",
    "test-file/test/cookies_test.js.html#lineNumber146",
    "Cookies #[Symbol.iterator]()",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber147",
    "Cookies #[Symbol.iterator]() should return a done iterator if the current document has no associated cookie",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber153",
    "Cookies #[Symbol.iterator]() should return a value iterator if the current document has associated cookies",
    "test"
  ],
  [
    "cookies#clear src/cookies.js~cookies#clear,cookies#clear",
    "test-file/test/cookies_test.js.html#lineNumber178",
    "Cookies #clear()",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber179",
    "Cookies #clear() should remove all the cookies associated with the current document",
    "test"
  ],
  [
    "cookies#get src/cookies.js~cookies#get,cookies#get",
    "test-file/test/cookies_test.js.html#lineNumber194",
    "Cookies #get()",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber195",
    "Cookies #get() should properly get the cookies associated with the current document",
    "test"
  ],
  [
    "cookies#getobject src/cookies.js~cookies#getobject,cookies#getobject",
    "test-file/test/cookies_test.js.html#lineNumber213",
    "Cookies #getObject()",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber214",
    "Cookies #getObject() should properly get the deserialized cookies associated with the current document",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber232",
    "Cookies #getObject() should return the default value if the value can't be deserialized",
    "test"
  ],
  [
    "cookies#has src/cookies.js~cookies#has,cookies#has",
    "test-file/test/cookies_test.js.html#lineNumber244",
    "Cookies #has()",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber245",
    "Cookies #has() should return `false` if the current document has an associated cookie with the specified key",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber249",
    "Cookies #has() should return `true` if the current document does not have an associated cookie with the specified key",
    "test"
  ],
  [
    "cookies#keys src/cookies.js~cookies#keys,cookies#keys",
    "test-file/test/cookies_test.js.html#lineNumber16",
    "Cookies #keys",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber17",
    "Cookies #keys should return an empty array if the current document has no associated cookie",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber21",
    "Cookies #keys should return the keys of the cookies associated with the current document",
    "test"
  ],
  [
    "cookies#length src/cookies.js~cookies#length,cookies#length",
    "test-file/test/cookies_test.js.html#lineNumber36",
    "Cookies #length",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber41",
    "Cookies #length should return the number of cookies associated with the current document",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber37",
    "Cookies #length should return zero if the current document has no associated cookie",
    "test"
  ],
  [
    "cookies#onchanges src/cookies.js~cookies#onchanges,cookies#onchanges",
    "test-file/test/cookies_test.js.html#lineNumber52",
    "Cookies #onChanges",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber58",
    "Cookies #onChanges should trigger an event when a cookie is added",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber95",
    "Cookies #onChanges should trigger an event when a cookie is removed",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber75",
    "Cookies #onChanges should trigger an event when a cookie is updated",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber115",
    "Cookies #onChanges should trigger an event when all the cookies are removed",
    "test"
  ],
  [
    "cookies#remove src/cookies.js~cookies#remove,cookies#remove",
    "test-file/test/cookies_test.js.html#lineNumber262",
    "Cookies #remove()",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber263",
    "Cookies #remove() should properly remove the cookies associated with the current document",
    "test"
  ],
  [
    "cookies#set src/cookies.js~cookies#set,cookies#set",
    "test-file/test/cookies_test.js.html#lineNumber281",
    "Cookies #set()",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber282",
    "Cookies #set() should properly set the cookies associated with the current document",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber294",
    "Cookies #set() should throw an error if the specified key is a reserved word",
    "test"
  ],
  [
    "cookies#setobject src/cookies.js~cookies#setobject,cookies#setobject",
    "test-file/test/cookies_test.js.html#lineNumber307",
    "Cookies #setObject()",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber308",
    "Cookies #setObject() should properly serialize and set the cookies associated with the current document",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber323",
    "Cookies #setObject() should throw an error if the specified key is a reserved word",
    "test"
  ],
  [
    "cookies#tostring src/cookies.js~cookies#tostring,cookies#tostring",
    "test-file/test/cookies_test.js.html#lineNumber336",
    "Cookies #toString()",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber341",
    "Cookies #toString() should return a format like \"<key>=<value>; expires=<expires>; domain=<domain>; path=<path>; secure\" for an initialized instance",
    "test"
  ],
  [
    "",
    "test-file/test/cookies_test.js.html#lineNumber337",
    "Cookies #toString() should return an empty string for a newly created instance",
    "test"
  ],
  [
    "src/cookie_module.js",
    "file/src/cookie_module.js.html",
    "src/cookie_module.js",
    "file"
  ],
  [
    "src/cookie_module.js~cookiemodule.annotations",
    "class/src/cookie_module.js~CookieModule.html#static-get-annotations",
    "src/cookie_module.js~CookieModule.annotations",
    "member"
  ],
  [
    "src/cookie_options.js",
    "file/src/cookie_options.js.html",
    "src/cookie_options.js",
    "file"
  ],
  [
    "src/cookie_options.js~cookieoptions#constructor",
    "class/src/cookie_options.js~CookieOptions.html#instance-constructor-constructor",
    "src/cookie_options.js~CookieOptions#constructor",
    "method"
  ],
  [
    "src/cookie_options.js~cookieoptions#domain",
    "class/src/cookie_options.js~CookieOptions.html#instance-member-domain",
    "src/cookie_options.js~CookieOptions#domain",
    "member"
  ],
  [
    "src/cookie_options.js~cookieoptions#expires",
    "class/src/cookie_options.js~CookieOptions.html#instance-member-expires",
    "src/cookie_options.js~CookieOptions#expires",
    "member"
  ],
  [
    "src/cookie_options.js~cookieoptions#path",
    "class/src/cookie_options.js~CookieOptions.html#instance-member-path",
    "src/cookie_options.js~CookieOptions#path",
    "member"
  ],
  [
    "src/cookie_options.js~cookieoptions#secure",
    "class/src/cookie_options.js~CookieOptions.html#instance-member-secure",
    "src/cookie_options.js~CookieOptions#secure",
    "member"
  ],
  [
    "src/cookie_options.js~cookieoptions#tojson",
    "class/src/cookie_options.js~CookieOptions.html#instance-method-toJSON",
    "src/cookie_options.js~CookieOptions#toJSON",
    "method"
  ],
  [
    "src/cookie_options.js~cookieoptions#tostring",
    "class/src/cookie_options.js~CookieOptions.html#instance-method-toString",
    "src/cookie_options.js~CookieOptions#toString",
    "method"
  ],
  [
    "src/cookies.js",
    "file/src/cookies.js.html",
    "src/cookies.js",
    "file"
  ],
  [
    "src/cookies.js~cookies#[symbol.iterator]",
    "class/src/cookies.js~Cookies.html#instance-method-[Symbol.iterator]",
    "src/cookies.js~Cookies#[Symbol.iterator]",
    "method"
  ],
  [
    "src/cookies.js~cookies#clear",
    "class/src/cookies.js~Cookies.html#instance-method-clear",
    "src/cookies.js~Cookies#clear",
    "method"
  ],
  [
    "src/cookies.js~cookies#constructor",
    "class/src/cookies.js~Cookies.html#instance-constructor-constructor",
    "src/cookies.js~Cookies#constructor",
    "method"
  ],
  [
    "src/cookies.js~cookies#defaults",
    "class/src/cookies.js~Cookies.html#instance-get-defaults",
    "src/cookies.js~Cookies#defaults",
    "member"
  ],
  [
    "src/cookies.js~cookies#get",
    "class/src/cookies.js~Cookies.html#instance-method-get",
    "src/cookies.js~Cookies#get",
    "method"
  ],
  [
    "src/cookies.js~cookies#getobject",
    "class/src/cookies.js~Cookies.html#instance-method-getObject",
    "src/cookies.js~Cookies#getObject",
    "method"
  ],
  [
    "src/cookies.js~cookies#has",
    "class/src/cookies.js~Cookies.html#instance-method-has",
    "src/cookies.js~Cookies#has",
    "method"
  ],
  [
    "src/cookies.js~cookies#keys",
    "class/src/cookies.js~Cookies.html#instance-get-keys",
    "src/cookies.js~Cookies#keys",
    "member"
  ],
  [
    "src/cookies.js~cookies#length",
    "class/src/cookies.js~Cookies.html#instance-get-length",
    "src/cookies.js~Cookies#length",
    "member"
  ],
  [
    "src/cookies.js~cookies#onchanges",
    "class/src/cookies.js~Cookies.html#instance-get-onChanges",
    "src/cookies.js~Cookies#onChanges",
    "member"
  ],
  [
    "src/cookies.js~cookies#remove",
    "class/src/cookies.js~Cookies.html#instance-method-remove",
    "src/cookies.js~Cookies#remove",
    "method"
  ],
  [
    "src/cookies.js~cookies#set",
    "class/src/cookies.js~Cookies.html#instance-method-set",
    "src/cookies.js~Cookies#set",
    "method"
  ],
  [
    "src/cookies.js~cookies#setobject",
    "class/src/cookies.js~Cookies.html#instance-method-setObject",
    "src/cookies.js~Cookies#setObject",
    "method"
  ],
  [
    "src/cookies.js~cookies#tostring",
    "class/src/cookies.js~Cookies.html#instance-method-toString",
    "src/cookies.js~Cookies#toString",
    "method"
  ],
  [
    "src/cookies.js~cookies.annotations",
    "class/src/cookies.js~Cookies.html#static-get-annotations",
    "src/cookies.js~Cookies.annotations",
    "member"
  ],
  [
    "src/cookies.js~cookies.parameters",
    "class/src/cookies.js~Cookies.html#static-get-parameters",
    "src/cookies.js~Cookies.parameters",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "test/cookie_options_test.js",
    "test-file/test/cookie_options_test.js.html",
    "test/cookie_options_test.js",
    "testFile"
  ],
  [
    "test/cookies_test.js",
    "test-file/test/cookies_test.js.html",
    "test/cookies_test.js",
    "testFile"
  ]
]